/**
 * Auto-generated by openapi-typescript from FastAPI /openapi.json
 * DO NOT EDIT — run `npm run generate` to regenerate from live API spec
 *
 * This is an expanded stub. After the API is running:
 *   cd packages/api-client && npm run generate
 */

export interface paths {
  '/auth/me': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['UserProfile']
          }
        }
        401: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/auth/login': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['LoginResponse']
          }
        }
        401: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/auth/logout': {
    post: {
      responses: {
        204: { content: never }
      }
    }
  }
  '/fleet/availability': {
    get: {
      parameters: {
        query: components['schemas']['AvailabilityQuery']
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['AvailabilityResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/fleet/availability/{locationId}': {
    get: {
      parameters: {
        path: { locationId: string }
        query?: {
          from?: string
          to?: string
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['AvailabilityResponse']
          }
        }
        404: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/fleet/vehicles': {
    get: {
      parameters: {
        query?: {
          location_id?: string
          status?: string
          class_code?: string
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['VehicleListResponse']
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['VehicleCreate']
        }
      }
      responses: {
        201: {
          content: {
            'application/json': components['schemas']['Vehicle']
          }
        }
        422: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/fleet/vehicles/{vehicleId}': {
    get: {
      parameters: {
        path: { vehicleId: string }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Vehicle']
          }
        }
        404: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
    patch: {
      parameters: {
        path: { vehicleId: string }
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['VehicleUpdate']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Vehicle']
          }
        }
      }
    }
  }
  '/reservations': {
    get: {
      parameters: {
        query?: {
          status?: string
          location_id?: string
          from_date?: string
          to_date?: string
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['ReservationListResponse']
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['ReservationCreate']
        }
      }
      responses: {
        201: {
          content: {
            'application/json': components['schemas']['ReservationResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
        422: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/reservations/{reservationId}': {
    get: {
      parameters: {
        path: { reservationId: string }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['ReservationResponse']
          }
        }
        404: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
    patch: {
      parameters: {
        path: { reservationId: string }
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ReservationUpdate']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['ReservationResponse']
          }
        }
      }
    }
    delete: {
      parameters: {
        path: { reservationId: string }
      }
      responses: {
        204: { content: never }
      }
    }
  }
  '/pricing/quote': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['RateQuoteRequest']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['RateQuoteResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/pricing/rate-codes': {
    get: {
      parameters: {
        query?: {
          status?: string
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['RateCodeListResponse']
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['RateCodeCreate']
        }
      }
      responses: {
        201: {
          content: {
            'application/json': components['schemas']['RateCode']
          }
        }
      }
    }
  }
  '/counter/checkout': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['CheckoutRequest']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['CheckoutResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/counter/check-in': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['CheckInRequest']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['CheckInResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/payments/pre-auth': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['InitiatePreAuthRequest']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['PreAuthResponse']
          }
        }
        400: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
        402: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/customers': {
    get: {
      parameters: {
        query?: {
          q?: string
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['CustomerListResponse']
          }
        }
      }
    }
  }
  '/customers/{customerId}': {
    get: {
      parameters: {
        path: { customerId: string }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Customer']
          }
        }
        404: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
  '/locations': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['LocationListResponse']
          }
        }
      }
    }
  }
  '/manage/{token}': {
    get: {
      parameters: {
        path: { token: string }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['ManagedReservation']
          }
        }
        401: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
        404: {
          content: {
            'application/json': components['schemas']['ProblemDetail']
          }
        }
      }
    }
  }
}

export interface components {
  schemas: {
    UserProfile: {
      user_id: string
      email: string
      first_name: string
      last_name: string
      role: string
      roles: string[]
      tenant_id: string
    }
    LoginRequest: {
      email: string
      password: string
    }
    LoginResponse: {
      user: components['schemas']['UserProfile']
      access_token: string
    }
    ProblemDetail: {
      type: string
      title: string
      status: number
      detail: string
      instance?: string
    }
    AvailabilityQuery: {
      pickup_location_id: string
      dropoff_location_id?: string
      pickup_date: string
      dropoff_date: string
      class_code?: string
    }
    AvailabilityClass: {
      classId: string
      classCode: string
      className: string
      description: string
      features: string[]
      imageUrl?: string
      availableCount: number
      baseDailyRate: number
      currencyCode: string
    }
    AvailabilityResponse: {
      locationId: string
      pickupDate: string
      dropoffDate: string
      classes: components['schemas']['AvailabilityClass'][]
      updatedAt: string
    }
    Vehicle: {
      vehicle_id: string
      plate: string
      vin: string
      make: string
      model: string
      year: number
      color: string
      class_code: string
      class_name: string
      status: string
      location_id: string
      location_name: string
      odometer: number
      fuel_level?: number
      notes?: string
      created_at: string
      updated_at: string
    }
    VehicleCreate: {
      plate: string
      vin: string
      make: string
      model: string
      year: number
      color: string
      class_code: string
      location_id: string
    }
    VehicleUpdate: {
      plate?: string
      status?: string
      location_id?: string
      odometer?: number
      notes?: string
    }
    VehicleListResponse: {
      items: components['schemas']['Vehicle'][]
      total: number
      page: number
      page_size: number
    }
    ReservationCreate: {
      pickup_location_id: string
      dropoff_location_id?: string
      pickup_date: string
      dropoff_date: string
      class_code: string
      rate_code?: string
      extras?: string[]
      customer: {
        first_name: string
        last_name: string
        email: string
        phone?: string
        dl_number?: string
        dl_state?: string
        dl_country?: string
      }
      payment_method_id?: string
    }
    ReservationUpdate: {
      pickup_date?: string
      dropoff_date?: string
      extras?: string[]
      status?: string
    }
    ReservationResponse: {
      reservation_id: string
      confirmation_number: string
      status: string
      source: string
      pickup_location_id: string
      dropoff_location_id: string
      pickup_date: string
      dropoff_date: string
      class_code: string
      class_name: string
      vehicle_id?: string
      customer: {
        customer_id: string
        first_name: string
        last_name: string
        email: string
        phone?: string
      }
      extras: Array<{
        code: string
        name: string
        daily_rate: number
      }>
      rate_summary: components['schemas']['RateQuoteResponse']
      created_at: string
      updated_at: string
    }
    ReservationListResponse: {
      items: components['schemas']['ReservationResponse'][]
      total: number
      page: number
      page_size: number
    }
    RateQuoteRequest: {
      pickup_location_id: string
      dropoff_location_id?: string
      pickup_date: string
      dropoff_date: string
      class_code: string
      rate_code?: string
      extras?: string[]
      loyalty_points_redemption?: number
    }
    RateQuoteLineItem: {
      description: string
      type: 'base' | 'extra' | 'fee' | 'tax' | 'discount'
      amount: number
      currency_code: string
    }
    RateQuoteResponse: {
      quote_id: string
      expires_at: string
      currency_code: string
      days: number
      base_rate_per_day: number
      subtotal: number
      extras_total: number
      fees_total: number
      taxes_total: number
      discount_total: number
      total: number
      line_items: components['schemas']['RateQuoteLineItem'][]
    }
    RateCode: {
      rate_code_id: string
      code: string
      name: string
      description?: string
      status: 'DRAFT' | 'ACTIVE' | 'EXPIRED'
      valid_from: string
      valid_to: string
      created_at: string
    }
    RateCodeCreate: {
      code: string
      name: string
      description?: string
      valid_from: string
      valid_to: string
    }
    RateCodeListResponse: {
      items: components['schemas']['RateCode'][]
      total: number
      page: number
      page_size: number
    }
    CheckoutRequest: {
      reservation_id: string
      vehicle_id: string
      odometer_out: number
      fuel_level_out: number
      extras?: string[]
      signature_data?: string
      email_ra_to?: string
    }
    CheckoutResponse: {
      rental_agreement_id: string
      reservation_id: string
      vehicle_id: string
      customer_id: string
      checkout_at: string
      odometer_out: number
      fuel_level_out: number
    }
    CheckInRequest: {
      rental_agreement_id: string
      odometer_in: number
      fuel_level_in: number
      damage_noted?: boolean
      damage_description?: string
    }
    CheckInResponse: {
      rental_agreement_id: string
      check_in_at: string
      final_charges: components['schemas']['RateQuoteResponse']
      payment_status: string
    }
    InitiatePreAuthRequest: {
      reservation_id: string
      amount: number
      currency_code: string
      payment_method_id: string
    }
    PreAuthResponse: {
      payment_id: string
      reservation_id: string
      status: 'AUTHORIZED' | 'FAILED'
      authorized_amount: number
      currency_code: string
      stripe_payment_intent_id?: string
    }
    Customer: {
      customer_id: string
      first_name: string
      last_name: string
      email: string
      phone?: string
      is_dnr: boolean
      dnr_reason?: string
      loyalty_tier?: 'BRONZE' | 'SILVER' | 'GOLD' | 'PLATINUM'
      loyalty_points?: number
      total_rentals: number
      created_at: string
    }
    CustomerListResponse: {
      items: components['schemas']['Customer'][]
      total: number
      page: number
      page_size: number
    }
    Location: {
      location_id: string
      name: string
      code: string
      address: string
      city: string
      state: string
      country: string
      timezone: string
      phone?: string
    }
    LocationListResponse: {
      items: components['schemas']['Location'][]
    }
    ManagedReservation: {
      reservation: components['schemas']['ReservationResponse']
      can_modify: boolean
      can_cancel: boolean
      modification_deadline?: string
      cancellation_deadline?: string
      invoice_url?: string
    }
  }
}
